# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- draft

pool:
  vmImage: 'ubuntu-latest'

steps:
  # instalando nodejs
  - task: NodeTool@0
    inputs:
      versionSpec: '11.x'
    displayName: 'instalando node js'
  # fin nodejs
  - script: |   
      npm install -g gatsby-cli
    displayName: 'instalando gatsby'

  - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'npm install'
        workingDirectory: '$(Build.SourcesDirectory)'
      displayName: 'npm install'

  - 
  



