# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: one
  value: initialValue

steps:
  # instalando nodejs
  - task: NodeTool@0
    inputs:
      versionSpec: '11.x'
    displayName: 'instalando node js'
  # fin nodejs
  - script: |   
      npm install -g gatsby-cli
    displayName: 'instalando gatsby'
  
  - task: Npm@1
    inputs:
      command: 'install'
      customRegistry: 'useFeed'
      customFeed: '$(default-feed)'
  
  - script: |
      gatsby build
    displayName: "gatsby build"
    env:
      REPO_NAME: $(REPO_NAME)
      REPO_OWNER: $(REPO_OWNER) 
      REPO_BRANCH: $(REPO_BRANCH) 
      
  # copiando archivos a salida
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/public'
      Contents: '**'
      TargetFolder: $(Build.ArtifactStagingDirectory)
      CleanTargetFolder: true
  #fin copiando archivos a salida

  #publicando artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: 'drop'
      publishLocation: 'container'
  #fin publicando artifacts

  



